## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [5]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [6]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [13]:
from sklearn.model_selection import train_test_split, KFold
X_train, X_test, y_train, y_test = train_test_split( X,y, test_size=0.5, random_state=0)
#train_data：所要划分的样本特征集

#train_target：所要划分的样本结果

#test_size：样本占比，如果是整数的话就是样本的数量

#random_state：是随机数的种子
#随机数种子：其实就是该组随机数的编号，在需要重复试验的时候，保证得到一组一样的随机数。比如你每次都填1，其他参数一样的情况下你得到的随机数组是一样的。但填0或不填，每次都会不一样。

#随机数的产生取决于种子，随机数和种子之间的关系遵从以下两个规则：
#种子不同，产生不同的随机数；种子相同，即使实例不同也产生相同的随机数。
#————————————————
#版权声明：本文为CSDN博主「Cherzhoucheer」的原创文章，遵循 CC 4.0 BY-SA 版权协议，转载请附上原文出处链接及本声明。
#原文链接：https://blog.csdn.net/CherDW/article/details/54881167

In [14]:
y_train

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0.])

In [15]:
X_train

array([[790, 791, 792, 793, 794],
       [955, 956, 957, 958, 959],
       [250, 251, 252, 253, 254],
       [  0,   1,   2,   3,   4],
       [470, 471, 472, 473, 474],
       [550, 551, 552, 553, 554],
       [475, 476, 477, 478, 479],
       [320, 321, 322, 323, 324],
       [835, 836, 837, 838, 839],
       [205, 206, 207, 208, 209],
       [345, 346, 347, 348, 349],
       [245, 246, 247, 248, 249],
       [240, 241, 242, 243, 244],
       [425, 426, 427, 428, 429],
       [ 65,  66,  67,  68,  69],
       [805, 806, 807, 808, 809],
       [115, 116, 117, 118, 119],
       [930, 931, 932, 933, 934],
       [675, 676, 677, 678, 679],
       [100, 101, 102, 103, 104],
       [ 75,  76,  77,  78,  79],
       [390, 391, 392, 393, 394],
       [520, 521, 522, 523, 524],
       [260, 261, 262, 263, 264],
       [500, 501, 502, 503, 504],
       [380, 381, 382, 383, 384],
       [ 15,  16,  17,  18,  19],
       [580, 581, 582, 583, 584],
       [820, 821, 822, 823, 824],
       [990, 9